# Generated by Django 5.1.5 on 2025-02-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0003_remove_profile_views_profile_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='65.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
